apiVersion: apps/v1
kind: Deployment
metadata:
  name: tocgenerator-deploy
  namespace: default
  labels:
    app: tocgenerator-deploy
spec:
  replicas: {{ .Values.spec.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tocgenerator-server
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tocgenerator-server
    spec:
      containers:        
        - name: tocgenerator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: BUILD_NUMBER
              value: {{ .Values.env.buildnumber }}
          # readinessProbe:
          #   tcpSocket:
          #     port: 80
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /toc/health
          #     port: 80
          #   initialDelaySeconds: 60
          #   periodSeconds: 60
          ports:
            - containerPort: 80